removing extension from icon per the error below
Run ./appimagetool-x86_64.AppImage --appimage-extract-and-run AppDir/
appimagetool, continuous build (commit 5735cc5), build <local dev build> built on 2023-03-08 22:52:04 UTC
WARNING: appstreamcli command is missing, please install it if you want to use AppStream metadata
/home/runner/work/cycles/cycles/AppDir/tylercode-cycles.desktop: error: (will be fatal in the future): value "icon.png" for key "Icon" in group "Desktop Entry" is an icon name with an extension, but there should be no extension as described in the Icon Theme Specification if the value is not an absolute path
Using architecture x86_64
icon.png{.png,.svg,.xpm} defined in desktop file but not found
For example, you could put a 256x256 pixel png into
/home/runner/work/cycles/cycles/AppDir/icon.png.png
/home/runner/work/cycles/cycles/AppDir should be packaged as Cycles-x86_64.AppImage
Error: Process completed with exit code 1.